-- 7.   As funções definidas até agora operam em um periodo entre 0 e n.
--      Defina versões alternativas dessas funções que trabalhem em um
--      periodo entre m e n, assumindo que n sempre é maior que m.
