-- 10.    Considere a sequência fibonacci de números: 0, 1, 1, 2, 3, 5, ...
--        cujos dois primeiros valores são 0 e 1, e os valores seguintes são
--        sempre a soma dos dois valores anteriores
--        (0+1=1, 1+1=2, 1+2=3, ...)
--        Escreva em Haskell a função fib sendo que fib n devolve o número que
--        está na posição n da sequência fibonacci
